select
    s.PERSONNUMMER as PERSONNUMMER
    ,s.FORNAMN as FORNAMN
    ,s.EFTERNAMN as EFTERNAMN
    ,sum(r.REGISTRERING_OMFATTNINGSVARDE) as OMFATTNING
    ,cast(cast(SUM(r.REGISTRERING_OMFATTNINGSVARDE) as decimal(8,2)) / 30 * 100 as decimal(6,0)) as OMFATTNING_PROCENT
    ,min(r.STUDIEPERIOD_STARTDATUM)       as STUDIEPERIOD_STARTDATUM
    ,max(r.STUDIEPERIOD_SLUTDATUM)        as STUDIEPERIOD_SLUTDATUM
from
    UPPFOLJNING.IO_REGISTRERING r
    inner join UPPFOLJNING.BI_UTBILDNINGSTYPER t on r.UTBILDNINGSTYP_KOD = t.UTBILDNINGSTYP_KOD
    inner join UPPFOLJNING.IO_STUDENTUPPGIFTER s on r.STUDENT_UID = s.STUDENT_UID
where
    t.GRUNDTYP = 'KURS'
    and r.STUDIEPERIOD_STARTDATUM >= :#${header.terminStartDatum}
    and r.STUDIEPERIOD_SLUTDATUM < :#${header.terminSlutDatum}
    and (r.ENHET_KOD = 'HP' or r.ENHET_KOD = 'HP-K')
--    and r.REGTYP <> 'OM'
group by
    r.STUDENT_UID
    ,s.PERSONNUMMER
    ,s.FORNAMN
    ,s.EFTERNAMN
order by
    s.PERSONNUMMER asc
