SELECT
     r.STUDENT_UID,
     r.enhet_kod,
     r.YTTERSTA_KURSPAKETERING_KOD,
     r.YTTERSTA_KURSPAKETERING_SV,
     r.YTTERSTA_KURSPAKETERINGSTYP_KOD,
     SUM(r.REGISTRERING_OMFATTNINGSVARDE) AS REGISTRERAD_OMFATTNING,
     MIN(r.STUDIEPERIOD_STARTDATUM)       AS STUDIEPERIOD_STARTDATUM,
     MAX(r.STUDIEPERIOD_SLUTDATUM)        AS STUDIEPERIOD_SLUTDATUM
   FROM UPPFOLJNING.IO_REGISTRERING r
   INNER JOIN UPPFOLJNING.IO_STUDENTUPPGIFTER stud ON stud.STUDENT_UID = r.STUDENT_UID
   WHERE
     r.STUDIEPERIOD_STARTDATUM >= :#${header.startDatum}
     AND r.STUDIEPERIOD_SLUTDATUM <= :#${header.slutDatum}
     AND r.ENHET_KOD = 'HP'
     AND r.REGTYP <> 'OM'
   GROUP BY r.STUDENT_UID, r.enhet_kod, r.YTTERSTA_KURSPAKETERING_KOD,
     r.YTTERSTA_KURSPAKETERING_SV, r.YTTERSTA_KURSPAKETERINGSTYP_KOD