pr: none
trigger:
  branches:
    include:
      - '*'

variables:
  - group: integration-iac-deployment-settings
  - name: dockerfilePath
    value: '$(Pipeline.Workspace)/github/AzDockerfile'
  - name: appName
    value: integral-mecenat-old-ref
  - name: imageName
    value: integral-mecenat-old
  - name: tag
    value: '${BUILD_BUILDNUMBER}_${BUILD_SOURCEVERSION:0:8}'
  - name: parametersFileName
    value: ref.parameters.json

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    displayName: 'Azure CLI - check path'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        pwd
        ls

  #- task: Maven@3
  #  name: 'BuildPackage'
  #  displayName: Build and deploy artifact
  #  inputs:
  #    mavenPomFile: 'pom.xml'
  #    goals: 'clean package'
  #    options: '--no-transfer-progress'
  #    publishJUnitResults: true
  #    testResultsFiles: '**/surefire-reports/TEST-*.xml'
  #    javaHomeOption: 'JDKVersion'
  #    jdkVersionOption: '1.11'
  #    mavenVersionOption: 'Default'
  #    mavenAuthenticateFeed: false
  #    effectivePomSkip: false
  #    sonarQubeRunAnalysis: true
#
  #- template: templates/docker/build.yml@cet-iac
  #  parameters:
  #    runScan: true
  #    dockerFilePath: $(dockerfilePath)
  #    imageName: $(imageName)
  #    tag: $(tag)
#
  #- template: templates/docker/push.yml@cet-iac
  #  parameters:
  #    dockerFilePath: $(dockerfilePath)
  #    imageName: $(imageName)
  #    tag: $(tag)
#
  #- template: templates/app-service/update-image.yml@cet-iac
  #  parameters:
  #    parametersFileName: $(parametersFileName)
  #    appName: $(appName)
  #    imageName: $(imageName)
  #    tag: $(tag)
  #    isApi: false
  #    hasSlot: false
#